// Touch press feedback.
//
// On a touch device there's no hover, so the desktop hover styles are mirrored
// onto a `.is-pressed` class (see styles/touch-press.css, generated by
// scripts/gen-touch-press.mjs). This module puts that class on the pressed
// element — and on its ancestors, so rules written against a wrapper still
// match — for as long as the finger is down AND still on the control.
//
// Sliding off cancels: the class comes off and the tap that the browser would
// otherwise synthesise is swallowed, so the button doesn't fire.

const PRESSED = 'is-pressed'

// The element a press "belongs to" — its box is what the finger has to stay
// inside. Falls back to the event target for anything not listed.
const CONTROL = [
  'button', 'a', '[role="button"]',
  '.swipe-row', '.card-context-item', '.save-to-option', '.search-result-row',
  '.dots-menu', '.canvas-link', '.add-toast', '.checkbox-wrap', '.todo-attach-item',
  '.cal-cell', '.link-tile', '.toolbar-left', '.project-input-wrap',
  '.mbar-circle', '.link-input-stack', '.detail-footer-cell',
].join(', ')

export function installPressState() {
  let chain = []          // the elements currently carrying the class
  let control = null      // the element whose box the finger must stay inside
  let pointerId = null
  let outside = false     // the finger has left the control's box

  const clear = () => {
    chain.forEach(el => el.classList.remove(PRESSED))
    chain = []
  }

  const end = () => {
    clear()
    control = null
    pointerId = null
  }

  const onDown = (e) => {
    if (e.pointerType === 'mouse' || pointerId !== null) return
    const target = e.target instanceof Element ? e.target : null
    if (!target) return
    control = target.closest(CONTROL) || target
    pointerId = e.pointerId
    outside = false
    // All the way up, so a rule written against any wrapper matches — the box
    // often belongs to a container rather than the control itself. Where that
    // would double up (a canvas link inside a row), the CSS suppresses the outer
    // one with :has().
    for (let el = target; el && el !== document.body; el = el.parentElement) {
      el.classList.add(PRESSED)
      chain.push(el)
    }
  }

  const onMove = (e) => {
    if (e.pointerId !== pointerId || !control) return
    const r = control.getBoundingClientRect()
    const inside = e.clientX >= r.left && e.clientX <= r.right &&
                   e.clientY >= r.top && e.clientY <= r.bottom
    if (!inside && !outside) {
      // Off the control: drop the highlight and don't let it fire
      outside = true
      clear()
    } else if (inside && outside) {
      outside = false
    }
  }

  const onUp = (e) => {
    if (e.pointerId !== pointerId) return
    // Only a release that actually lands off the control is swallowed. Anything
    // else — a scroll that stole the gesture, a jitter that came back — must let
    // the tap through, or controls that open on click stop responding.
    if (outside && control) {
      const r = control.getBoundingClientRect()
      const off = e.clientX < r.left || e.clientX > r.right ||
                  e.clientY < r.top || e.clientY > r.bottom
      if (off) swallowNextTap()
    }
    end()
  }

  const onCancel = (e) => {
    if (e.pointerId !== pointerId) return
    end()
  }

  // The browser still synthesises mousedown/click after a touch that ended off
  // its start element on some platforms — eat the next one.
  function swallowNextTap() {
    const eat = (ev) => { ev.stopPropagation(); ev.preventDefault() }
    const types = ['mousedown', 'click']
    types.forEach(t => document.addEventListener(t, eat, true))
    setTimeout(() => types.forEach(t => document.removeEventListener(t, eat, true)), 300)
  }

  document.addEventListener('pointerdown', onDown, true)
  document.addEventListener('pointermove', onMove, true)
  document.addEventListener('pointerup', onUp, true)
  document.addEventListener('pointercancel', onCancel, true)
  // A scroll steals the gesture: drop the highlight, but leave the tap alone —
  // the browser decides whether a scrolled touch still counts as a tap.
  window.addEventListener('scroll', () => { if (pointerId !== null) clear() }, true)
}
