// Touch press feedback.
//
// On a touch device there's no hover, so the desktop hover styles are mirrored
// onto a `.is-pressed` class (see styles/touch-press.css, generated by
// scripts/gen-touch-press.mjs). This module puts that class on the pressed
// element — and on its ancestors, so rules written against a wrapper still
// match — for as long as the finger is down AND still on the control.
//
// Sliding off cancels: the class comes off and the tap that the browser would
// otherwise synthesise is swallowed, so the button doesn't fire.

const PRESSED = 'is-pressed'

// The element a press "belongs to" — its box is what the finger has to stay
// inside. Falls back to the event target for anything not listed.
const CONTROL = [
  'button', 'a', '[role="button"]',
  '.swipe-row', '.card-context-item', '.save-to-option', '.search-result-row',
  '.dots-menu', '.canvas-link', '.add-toast', '.checkbox-wrap', '.todo-attach-item',
  '.cal-cell', '.link-tile', '.toolbar-left', '.project-input-wrap', '.add-input',
].join(', ')

export function installPressState() {
  let chain = []          // the elements currently carrying the class
  let control = null      // the element whose box the finger must stay inside
  let pointerId = null
  let cancelled = false

  const clear = () => {
    chain.forEach(el => el.classList.remove(PRESSED))
    chain = []
  }

  const end = () => {
    clear()
    control = null
    pointerId = null
  }

  const onDown = (e) => {
    if (e.pointerType === 'mouse' || pointerId !== null) return
    const target = e.target instanceof Element ? e.target : null
    if (!target) return
    control = target.closest(CONTROL) || target
    pointerId = e.pointerId
    cancelled = false
    // Up to (and including) the control, so a rule written against it — or an
    // inner wrapper — matches. It stops there: pressing a canvas link inside a
    // row shouldn't light the whole row up as well.
    for (let el = target; el; el = el.parentElement) {
      el.classList.add(PRESSED)
      chain.push(el)
      if (el === control || el === document.body) break
    }
  }

  const onMove = (e) => {
    if (e.pointerId !== pointerId || !control) return
    const r = control.getBoundingClientRect()
    const inside = e.clientX >= r.left && e.clientX <= r.right &&
                   e.clientY >= r.top && e.clientY <= r.bottom
    if (!inside && !cancelled) {
      // Off the control: drop the highlight and don't let it fire
      cancelled = true
      clear()
    } else if (inside && cancelled) {
      cancelled = false
    }
  }

  const onUp = (e) => {
    if (e.pointerId !== pointerId) return
    if (cancelled) swallowNextTap()
    end()
  }

  const onCancel = (e) => {
    if (e.pointerId !== pointerId) return
    end()
  }

  // The browser still synthesises mousedown/click after a touch that ended off
  // its start element on some platforms — eat the next one.
  function swallowNextTap() {
    const eat = (ev) => { ev.stopPropagation(); ev.preventDefault() }
    const types = ['mousedown', 'mouseup', 'click']
    types.forEach(t => document.addEventListener(t, eat, true))
    setTimeout(() => types.forEach(t => document.removeEventListener(t, eat, true)), 400)
  }

  document.addEventListener('pointerdown', onDown, true)
  document.addEventListener('pointermove', onMove, true)
  document.addEventListener('pointerup', onUp, true)
  document.addEventListener('pointercancel', onCancel, true)
  // A scroll steals the gesture — treat it as leaving the control
  window.addEventListener('scroll', () => { if (pointerId !== null) { cancelled = true; clear() } }, true)
}
